server {
  listen 80;
  index index.html;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/api/;
  }

  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/admin/;
  }

  # Статика Django
  location /static/admin/ {
    alias /backend_static/admin/;
  }

  # Статика фронтенда
  location /static/ {
    alias /frontend_static/static/;
  }

  # Медиа-файлы
  location /media/ {
    alias /media/;
    expires max;
    access_log off;
  }

  # Главная страница фронтенда
  location / {
    alias /frontend_static/;
    try_files $uri $uri/ /index.html;
  }
}